name: pose_view_macos
description: MacOS implementation of the pose_view plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: pose_view
    platforms:
      macos:
        pluginClass: PoseViewPlugin
        dartPluginClass: PoseViewMacOS

dependencies:
  flutter:
    sdk: flutter
  pose_view_platform_interface:
    path: ../pose_view_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
